# Generated by Django 4.1.1 on 2022-10-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=16)),
            ],
        ),
    ]
