# Generated by Django 4.1.3 on 2022-11-03 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import pixelmate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=30)),
                ("Description", models.CharField(max_length=50)),
                ("ProjectImage", models.CharField(max_length=100)),
                ("Difficulty_level", models.CharField(max_length=10)),
                ("Url", models.CharField(max_length=50)),
                (
                    "Technology",
                    djongo.models.fields.ArrayField(
                        model_container=pixelmate.models.Tech,
                        model_form_class=pixelmate.models.TechForm,
                    ),
                ),
                (
                    "Progress",
                    djongo.models.fields.ArrayField(
                        model_container=pixelmate.models.Step,
                        model_form_class=pixelmate.models.StepForm,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Username", models.CharField(max_length=30)),
                ("Email", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectOnGoing",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=30)),
                ("Description", models.CharField(max_length=50)),
                ("ProjectImage", models.CharField(max_length=100)),
                (
                    "CreatedDate",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("Url", models.CharField(max_length=50)),
                (
                    "Technology",
                    djongo.models.fields.ArrayField(
                        model_container=pixelmate.models.Tech,
                        model_form_class=pixelmate.models.TechForm,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Signup",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=30)),
                ("Username", models.CharField(max_length=30)),
                ("Email", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Task",
                    djongo.models.fields.ArrayField(
                        model_container=pixelmate.models.Work,
                        model_form_class=pixelmate.models.WorkForm,
                    ),
                ),
                (
                    "Project",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pixelmate.projectongoing",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projectongoing",
            name="Username",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pixelmate.signup",
            ),
        ),
        migrations.CreateModel(
            name="ProjectCompleted",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=30)),
                ("Description", models.CharField(max_length=50)),
                ("ProjectImage", models.CharField(max_length=100)),
                (
                    "CreatedDate",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "CompletedDate",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "Work",
                    djongo.models.fields.ArrayField(
                        model_container=pixelmate.models.Work,
                        model_form_class=pixelmate.models.WorkForm,
                    ),
                ),
                ("Url", models.CharField(max_length=50)),
                (
                    "Technology",
                    djongo.models.fields.ArrayField(
                        model_container=pixelmate.models.Tech,
                        model_form_class=pixelmate.models.TechForm,
                    ),
                ),
                (
                    "Username",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pixelmate.signup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompleteChallenge",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=30)),
                ("Description", models.CharField(max_length=50)),
                ("Difficulty_level", models.CharField(max_length=10)),
                ("ProjectImage", models.CharField(max_length=100)),
                (
                    "AcceptedDate",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "CompletedDate",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("Url", models.CharField(max_length=50)),
                (
                    "Technology",
                    djongo.models.fields.ArrayField(
                        model_container=pixelmate.models.Tech,
                        model_form_class=pixelmate.models.TechForm,
                    ),
                ),
                (
                    "Progress",
                    djongo.models.fields.ArrayField(
                        model_container=pixelmate.models.Step,
                        model_form_class=pixelmate.models.StepForm,
                    ),
                ),
                (
                    "Challenge",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pixelmate.challenge",
                    ),
                ),
                (
                    "Username",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pixelmate.signup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcceptChallenge",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=30)),
                ("Description", models.CharField(max_length=50)),
                ("Difficulty_level", models.CharField(max_length=10)),
                ("ProjectImage", models.CharField(max_length=100)),
                ("CurrentTask", models.IntegerField(default=0)),
                (
                    "AcceptedDate",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("Url", models.CharField(max_length=50)),
                (
                    "Technology",
                    djongo.models.fields.ArrayField(
                        model_container=pixelmate.models.Tech,
                        model_form_class=pixelmate.models.TechForm,
                    ),
                ),
                (
                    "Progress",
                    djongo.models.fields.ArrayField(
                        model_container=pixelmate.models.Step,
                        model_form_class=pixelmate.models.StepForm,
                    ),
                ),
                (
                    "Challenge",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pixelmate.challenge",
                    ),
                ),
                (
                    "Username",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pixelmate.signup",
                    ),
                ),
            ],
        ),
    ]
