# Generated by Django 3.1.12 on 2022-10-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixelmate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptchallenge',
            name='Challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pixelmate.challenge'),
        ),
        migrations.AddField(
            model_name='completechallenge',
            name='Challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pixelmate.challenge'),
        ),
    ]
