# Generated by Django 3.1.12 on 2022-10-27 11:42

from django.db import migrations, models
import djongo.models.fields
import pixelmate.models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelmate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=50)),
                ('Difficulty_level', models.CharField(max_length=10)),
                ('Url', models.CharField(max_length=50)),
                ('Technology', djongo.models.fields.ArrayField(model_container=pixelmate.models.Tech, model_form_class=pixelmate.models.TechForm)),
                ('Progress', djongo.models.fields.ArrayField(model_container=pixelmate.models.Step, model_form_class=pixelmate.models.StepForm)),
            ],
        ),
    ]
