# Generated by Django 3.1.12 on 2022-11-01 16:04

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('pixelmate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(storage=djongo.storage.GridFSStorage(base_url='http://localhost:8000/myfiles/', collection='myfiles'), upload_to='authors')),
            ],
        ),
    ]
