# Generated by Django 3.1.12 on 2022-11-05 13:12

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('pixelmate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectImage', models.ImageField(storage=djongo.storage.GridFSStorage(base_url='F:\\GIT\\pixelmate\\backendmyfiles/', collection='myfiles'), upload_to='project')),
            ],
        ),
    ]
