# Generated by Django 3.1.12 on 2022-11-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelmate', '0002_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
